apiVersion: v1
kind: Service
metadata:
  name: sms-campaign-manager-service
spec:
  selector:
    app: sms-campaign-manager
  ports:
    - protocol: TCP
      port: 8080  # The port to expose on the service
      targetPort: 8080  # The port the microservice listens on in the container
  type: LoadBalancer  # Use NodePort or ClusterIP as needed
