// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewCampaign struct {
	Name      string `json:"name"`
	StartTime string `json:"startTime"`
}

type NewSegment struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewTemplate struct {
	Name    string `json:"name"`
	Content string `json:"content"`
}
